# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('num', models.IntegerField(verbose_name='最大人数')),
                ('classes', models.CharField(max_length=30, verbose_name='班级')),
            ],
            options={
                'verbose_name': '实验',
                'verbose_name_plural': '实验',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=30, verbose_name='班级')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('ex_name', models.CharField(max_length=64, verbose_name='实验名称')),
                ('grade', models.CharField(max_length=30, verbose_name='成绩')),
                ('commment', models.CharField(max_length=64, verbose_name='评语')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
            },
        ),
    ]
