# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('forenoon_in', models.TimeField(blank=True, null=True)),
                ('forenoon_out', models.TimeField(blank=True, null=True)),
                ('afternoon_in', models.TimeField(blank=True, null=True)),
                ('afternoon_out', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postgraduate',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='postgraduate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='management.Teacher'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='postgraduate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Postgraduate'),
        ),
    ]
