# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('excuse', models.TextField()),
                ('state', models.NullBooleanField()),
                ('time_of_submission', models.DateTimeField()),
                ('time_of_processing', models.DateTimeField(blank=True, null=True)),
                ('postgraduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Postgraduate')),
            ],
        ),
    ]
