# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 16:42
from __future__ import unicode_literals

import brief.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=brief.models.brief_directory_path)),
                ('commit', models.BooleanField(default=False)),
                ('have_read', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Postgraduate')),
            ],
        ),
    ]
