# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcheckinsetting',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
