# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckInSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('week_option', models.CharField(max_length=7)),
                ('times', models.IntegerField(default=1)),
                ('time1_start', models.TimeField()),
                ('time1_end', models.TimeField()),
                ('time2_start', models.TimeField(blank=True, null=True)),
                ('time2_end', models.TimeField(blank=True, null=True)),
                ('time3_start', models.TimeField(blank=True, null=True)),
                ('time3_end', models.TimeField(blank=True, null=True)),
                ('time4_start', models.TimeField(blank=True, null=True)),
                ('time4_end', models.TimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Teacher')),
            ],
        ),
        migrations.RenameField(
            model_name='dailycheckin',
            old_name='afternoon_in',
            new_name='check1',
        ),
        migrations.RenameField(
            model_name='dailycheckin',
            old_name='afternoon_out',
            new_name='check2',
        ),
        migrations.RenameField(
            model_name='dailycheckin',
            old_name='forenoon_in',
            new_name='check3',
        ),
        migrations.RenameField(
            model_name='dailycheckin',
            old_name='forenoon_out',
            new_name='check4',
        ),
    ]
