# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_auto_20180313_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckinsetting',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkin.Computer'),
        ),
    ]
