# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_dailycheckinsetting_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckinsetting',
            name='times',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
