# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20180206_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcheckin',
            name='target',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='checkin.CheckInSetting'),
            preserve_default=False,
        ),
    ]
