# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20180314_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckinsetting',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Teacher', unique=True),
        ),
    ]
