# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('excuse', models.TextField()),
                ('state', models.NullBooleanField()),
                ('time_of_submission', models.DateTimeField()),
                ('time_of_processing', models.DateTimeField(blank=True, null=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Teacher')),
                ('postgraduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Postgraduate')),
            ],
        ),
    ]
