# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名')),
            ],
            options={
                'verbose_name': '课题组',
                'verbose_name_plural': '课题组',
            },
        ),
        migrations.CreateModel(
            name='Postgraduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30, unique=True, verbose_name='学号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('salt', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '研究生',
                'verbose_name_plural': '研究生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('salt', models.CharField(max_length=64)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Group', verbose_name='课题组')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.AddField(
            model_name='postgraduate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Teacher', verbose_name='导师'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_group', to='account.Teacher', verbose_name='组长'),
        ),
    ]
