# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgraduate',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
    ]
